mysql:
  deployment:
    image: mysql:5.6
  
phpmyadmin:
  deployment:
    image: phpmyadmin/phpmyadmin
    env:
      PMA_ABSOLUTE_URI:
        value: https://erfan-mazraei-nl-rg3.maxtld.dev/dbadmin
  ingress:
    rules:
      host: erfan-mazraei-nl-rg3.maxtld.dev
