mysql:
  deployment:
    spec:
      containers:
        image: mysql:5.6
      revisionHistoryLimit: 15

phpmyadmin:
  deployment:
    spec:
      revisionHistoryLimit: 5
      containers:
        image: phpmyadmin/phpmyadmin
        env:
          PMA_ABSOLUTE_URI:
            value: https://erfan-mazraei-nl-rg3.maxtld.dev/dbadmin
  ingress:
    rules:
      host: erfan-mazraei-nl-rg3.maxtld.dev
