mysql:
  deployment:
    spec:
      containers:
        image: mysql:5.6
      revisionHistoryLimit: 15

phpmyadmin:
  deployment:
    spec:
      revisionHistoryLimit: 5
      containers:
        image: phpmyadmin/phpmyadmin
        env:
          PMA_ABSOLUTE_URI:
            value: https://erfan-mazraei-nl-rg3.maxtld.dev/dbadmin
  ingress:
    spec:
      tls:
        hosts: erfan-mazraei-nl-rg3.maxtld.dev
      rules:
        host: erfan-mazraei-nl-rg3.maxtld.dev

wordpress:
  deployment:
    spec:
      revisionHistoryLimit: 15
        containers:
          image: wordpress:5.1.1-php7.3-apache
  ingress:
    spec:
      tls:
        hosts: erfan-mazraei-nl-rg3.maxtld.dev
      rules:
        host: erfan-mazraei-nl-rg3.maxtld.dev

