{{- if .Values.jira.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "jira-helm.fullname" . }}-jira
  labels:
    {{- include "jira-helm.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "jira-helm.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "jira-helm.labels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap-jira.yaml") . | sha256sum }}
    spec:
      containers:
      - name: jira
        image: {{ .Values.jira.image.repository }}:{{ .Values.jira.image.tag }}
        imagePullPolicy: {{ .Values.jira.image.pullPolicy }}
        envFrom:
        - configMapRef:
            name: {{ include "jira-helm.fullname" . }}-jira-config
        ports:
        - containerPort: {{ .Values.jira.service.port }}
          name: http
        volumeMounts:
        - name: data
          mountPath: /var/jira
        resources:
          {{- toYaml .Values.jira.resources | nindent 12 }}
        livenessProbe:
          httpGet:
            path: {{ .Values.jira.probe.liveness.path }}
            port: http
          initialDelaySeconds: {{ .Values.jira.probe.liveness.initialDelaySeconds }}
          periodSeconds: {{ .Values.jira.probe.liveness.periodSeconds }}
          timeoutSeconds: {{ .Values.jira.probe.liveness.timeoutSeconds }}
          failureThreshold: {{ .Values.jira.probe.liveness.failureThreshold }}
        readinessProbe:
          httpGet:
            path: {{ .Values.jira.probe.readiness.path }}
            port: http
          initialDelaySeconds: {{ .Values.jira.probe.readiness.initialDelaySeconds }}
          periodSeconds: {{ .Values.jira.probe.readiness.periodSeconds }}
          timeoutSeconds: {{ .Values.jira.probe.readiness.timeoutSeconds }}
          failureThreshold: {{ .Values.jira.probe.readiness.failureThreshold }}
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: {{ include "jira-helm.fullname" . }}-jira-pvc
      {{- with .Values.jira.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.jira.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.jira.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}