---
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: wordpress
  name: mysql-pv
spec:
  storageClassName: "A"
  capacity:  
    storage: 5Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/mysqldata"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: wordpress
  name: mysql-pvc
spec:
  storageClassName: "A" 
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
      