apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: wordpress
  name: mysql-pv
spec:
  storageClassName: ""
  capacity:  
    storage: 5Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/mysqldata"