apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: wordpress
  name: mysql-pvc
spec:
  storageClassName: "" 
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi