apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: wordpress
  labels:
    app: mysql-wordpress
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      dnsPolicy: "None"
      dnsConfig:
        nameservers: ["10.233.0.3"]
        searches:
        - wordpress.svc.cluster.local
        - svc.cluster.local
        - cluster.local
        options:
        - name: ndots
          value: "5"
      volumes:
      - name: mysqlpod-pvc
        persistentVolumeClaim:
          claimName: mysql-pvc
      - name: mysql-initdb
        configMap:
          name: mysql-initdb-config

      containers:
      - name: mysql
        image: mysql:5.6
        ports:
        - containerPort: 3306
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: mysqlpod-pvc
        - mountPath: /docker-entrypoint-initdb.d
          name: mysql-initdb
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: wordpress-secret
              key: mrp
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: wordpress-secret
              key: mdb
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: wordpress-secret
              key: mu
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: wordpress-secret
              key: mp

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb-config
data:
  initdb.sql: |
    GRANT ALL PRIVILEGES ON wpdb.* TO 'sonu'@'%' IDENTIFIED BY 'redhat';
    GRANT ALL PRIVILEGES ON wpdb.* TO '0'@'%' IDENTIFIED BY 'redhat';
