apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: wordpress
  labels:
    app: mysql-wordpress
  name: mysql
spec:
  replicas: 1
  revisionHistoryLimit: {{ .Values.mysql.deployment.spec.revisionHistoryLimit }}
  strategy:
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      dnsPolicy: "None"
      dnsConfig:
        nameservers: ["10.233.0.3"]
        searches:
        - wordpress.svc.cluster.local
        - svc.cluster.local
        - cluster.local
        options:
        - name: ndots
          value: "5"
      volumes:
      - name: mysqlpod-pvc
        persistentVolumeClaim:
          claimName: mysql-pvc
      - name: mysql-initdb
        configMap:
          name: mysql-initdb-config

      containers:
      - name: mysql
        image: {{ .Values.mysql.deployment.spec.containers.image }}
        imagePullPolicy: "IfNotPresent"
        resources:
          limits:
            memory: 700Mi
            cpu: 500m
          requests:
            memory: 10Mi
            cpu: 10m
        ports:
        - containerPort: 3306
        startupProbe:
          tcpSocket:
            port: 3306
          initialDelaySeconds: 180
          periodSeconds: 10
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 2
        livenessProbe:
          tcpSocket:
            port: 3306
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 2
        readinessProbe:
          tcpSocket:
            port: 3306
          initialDelaySeconds: 10
          periodSeconds: 20
          failureThreshold: 4
          successThreshold: 3
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: mysqlpod-pvc
        - mountPath: /docker-entrypoint-initdb.d
          name: mysql-initdb
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: wordpress-secret
              key: mrp
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: wordpress-secret
              key: mdb
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: wordpress-secret
              key: mu
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: wordpress-secret
              key: mp

