apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: wordpress
  name: phpmyadmin-deployment
  labels:
    app: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      dnsPolicy: "None"
      dnsConfig:
        nameservers: ["10.233.0.3"]
        searches:
        - wordpress.svc.cluster.local
        - svc.cluster.local
        - cluster.local
        options:
        - name: ndots
          value: "5"
      containers:
        - name: phpmyadmin
          image: phpmyadmin/phpmyadmin
          ports:
            - containerPort: 80
          env:
            - name: PMA_HOST
              value: mysql-service
            - name: PMA_PORT
              value: "3306"
            - name: PMA_ABSOLUTE_URI
              value: https://erfan-mazraei-nl-rg3.maxtld.dev/dbadmin
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wordpress-secret
                  key: mrp

