apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: wordpress
  labels:
    app: mysql-wordpress
  name: wordpress
spec:
  replicas: 1
  revisionHistoryLimit: {{ .Values.wordpress.deployment.spec.revisionHistoryLimit }}
  strategy:
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      dnsPolicy: "None"
      dnsConfig:
        nameservers: ["10.233.0.3"]
        searches:
        - wordpress.svc.cluster.local
        - svc.cluster.local
        - cluster.local
        options:
        - name: ndots
          value: "5"
      volumes:
      - name: wppod-pvc
        persistentVolumeClaim:
          claimName: wordpress-pvc
      containers:
      - image: {{ .Values.wordpress.deployment.spec.containers.image }}
        imagePullPolicy: "IfNotPresent"
        ports:
        - containerPort: 80
        name: wordpress
        resources:
          limits:
            memory: 700Mi
            cpu: 500m
          requests:
            memory: 10Mi
            cpu: 10m
        startupProbe:
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          initialDelaySeconds: 180
          periodSeconds: 10
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 2
        livenessProbe:
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 2
        readinessProbe:
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          failureThreshold: 4
          successThreshold: 3        
        env:
        - name: WORDPRESS_DB_HOST
          value: mysql-service
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: wordpress-secret
              key: mrp
        - name: WORDPRESS_DB_USER
          valueFrom:
            secretKeyRef:
              name: wordpress-secret
              key: mu
        - name: WORDPRESS_DB_NAME
          valueFrom:
            secretKeyRef:
              name: wordpress-secret
              key: mdb
        - name: WORDPRESS_CONFIG_EXTRA
          valueFrom:
            configMapKeyRef:
              name: wp-extra-config
              key: WORDPRESS_CONFIG_EXTRA

        volumeMounts:
        - mountPath: /var/www/html
          name: wppod-pvc