apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: wordpress
  labels:
    app: mysql-wordpress
  name: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      volumes:
      - name: wppod-pvc
        persistentVolumeClaim:
          claimName: wordpress-pvc
      containers:
      - image: wordpress:6.2.1-apache
        ports:
        - containerPort: 80
        name: wordpress
        env:
        - name: WORDPRESS_DB_HOST
          value: mysql-service
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: wordpress-secret
              key: mrp
        - name: WORDPRESS_DB_USER
          valueFrom:
            secretKeyRef:
              name: wordpress-secret
              key: mu

        volumeMounts:
        - mountPath: /var/www/html
          name: wppod-pvc