apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: wordpress
  name: wordpress-ingress
  annotations:
    cert-manager.io/cluster-issuer: "lets-encrypt"
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      rewrite ^(/wordpress)$ $1/ permanent;
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  tls:
    {{- range .Values.wordpress.ingress.spec.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: echo-tls-wordpress1
  rules:
  - host: {{ .Values.wordpress.ingress.spec.rules.host }}
    http:
      paths:
      - path: /wordpress(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: wordpress-service
            port:
              number: 80
