---
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: wordpress
  name: wordpress-pv
spec:
  storageClassName: "wpdata"
  capacity:
    storage: 3Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/wpdata"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: wordpress
  name: wordpress-pvc
spec:
  storageClassName: "wpdata"
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
      