apiVersion: v1
kind: Service
metadata:
  namespace: wordpress
  labels:
    app: mysql-wordpress
  name: wordpress-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: frontend
  type: ClusterIP